services:
  postgres-auth:
    container_name: "postgres-auth"
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data
    networks:
      - e-commerce-backend

  user-service:
    container_name: "user-service"
    build: ./user-service
    depends_on:
      postgres-auth:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      SERVER_PORT: 8081
      POSTGRES_URL: postgres://root:password@postgres-auth:5432/db?sslmode=disable
    ports:
      - "8081:8081"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user-service.entrypoints=web"
      - "traefik.http.services.user-service.loadbalancer.server.port=8081"
      - "traefik.http.routers.user-service.rule=PathPrefix(`/`)"
    volumes:
      - ./user-service:/app
    networks:
      - e-commerce-backend

  traefik:
    image: traefik:v3.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - e-commerce-backend

networks:
  e-commerce-backend:
    driver: bridge

volumes:
  postgres-auth-data:
